---
- name: Your Root-Level Playbook
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Check connection to organization
      ansible.builtin.import_tasks: tasks/getorg.yml

    - name: Check on specific SSID
      ansible.builtin.import_tasks:  tasks/SSID.yml
       
